export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const DELETE_TRANSACTION_SUCCEEDED = "DELETE_TRANSACTION_SUCCEEDED";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const ADD_TRANSACTION_SUCCEEDED = "ADD_TRANSACTION_SUCCEEDED";
